name: ci-cd

on:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest

<<<<<<< HEAD
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}

=======
>>>>>>> 70a05eb (chore: add package-lock.json for CI)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Run unit tests
        run: npm test -- --ci

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
<<<<<<< HEAD
          images: ${{ env.DOCKERHUB_USERNAME }}/hola-mundo
=======
          images: ${{ secrets.DOCKERHUB_USERNAME }}/hola-mundo
>>>>>>> 70a05eb (chore: add package-lock.json for CI)
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
<<<<<<< HEAD
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
=======
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
>>>>>>> 70a05eb (chore: add package-lock.json for CI)

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Trigger Render deploy (optional)
<<<<<<< HEAD
        if: ${{ env.RENDER_DEPLOY_HOOK != '' }}
        run: |
          curl -fsSL -X POST "${{ env.RENDER_DEPLOY_HOOK }}"
=======
        if: ${{ secrets.RENDER_DEPLOY_HOOK != '' }}
        run: |
          curl -fsSL -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
>>>>>>> 70a05eb (chore: add package-lock.json for CI)
