name: ci-cd

on:
  push:
    branches:
      - main

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Instala con lockfile si existe; si no, genera uno
      - name: Install deps (smart)
        shell: bash
        run: |
          if [ -f package-lock.json ]; then
            echo "Using npm ci"
            npm ci
          else
            echo "No package-lock.json found. Using npm install and generating it."
            npm install
            npm i --package-lock-only
          fi

      - name: Run unit tests
        run: npm test -- --ci

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_USERNAME }}/hola-mundo
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Login to Docker Hub
        if: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push image
        if: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Trigger Render deploy (optional)
        if: ${{ env.RENDER_DEPLOY_HOOK != '' }}
        run: |
          echo "Calling Render deploy hook..."
          STATUS=$(curl -s -o /tmp/render_resp.txt -w "%{http_code}" -X POST "$RENDER_DEPLOY_HOOK" || true)
          echo "HTTP status: $STATUS"
          echo "Response body:"
          cat /tmp/render_resp.txt || true

          # No marcar fallo del job si el hook devuelve >=400
          # (Render puede haber aceptado el deploy internamente o tener política de auth distinta)
          if [ "$STATUS" -ge 400 ]; then
            echo "Warning: Render hook returned HTTP $STATUS. Ignorando el error para no romper el pipeline."
          fi
      - name: Health check (optional)
        env:
          APP_URL: https://devops-hola-mundo-78lm.onrender.com/
        run: |
          echo "Comprobando $APP_URL..."
          for i in {1..30}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" "$APP_URL")
            if [ "$code" = "200" ]; then
              echo "OK (200). App arriba."
              exit 0
            fi
            echo "Intento $i: HTTP $code. Reintento en 10s..."
            sleep 10
          done
          echo "Timeout esperando 200 desde la app."
          exit 1
